-- CREAR BASE DE DATOS --
CREATE DATABASE GestionVentas;

-- CLAUSULA USE --
USE GestionVentas;

-- CREAR TABLA CLIENTE --
CREATE TABLE Clientes(
ID_Cliente INT NOT NULL IDENTITY (1,1) PRIMARY KEY,
-- USAMOS VARCHAR HASTA 100 CARACTERES PARA LOS NOMBRES PARA LIMITAR EL ESPACIO --
Nombre VARCHAR(100) NOT NULL,
-- USAMOS TEXT PARA PERFIL CON CARACTERES ILIMITADOS, YA QUE SON TEXTO MUY LARGOS --
Perfil_bio TEXT NOT NULL,
-- USAMOS DATE PARA EL REGISTRO DEL CLIENTE Y NO DATETIME YA QUE NO NOS IMPORTA EL INGRESO EXACTO (HORAS) --
Fecha_registro DATE NOT NULL
)

-- CREAR TABLA PRODCUTOS --
CREATE TABLE Productos(
ID_Producto INT NOT NULL IDENTITY (1,1) PRIMARY KEY,
Descripcion VARCHAR(255) NOT NULL,
Precio DECIMAL(10,2) NOT NULL,
Esta_activo VARCHAR(2) NOT NULL
);




